---
- hosts: [dbservers]
  become: yes
  remote_user: <AD_ID>
  become_user: root
  tasks:
    - name: Remove rpm packages for MySQL Enterprise Edition
      yum:
        name: mysql-commercial*
        state: absent
